/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUTHCHECK_H_RPCGEN
#define _AUTHCHECK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct auth_check2_out {
	int ret;
};
typedef struct auth_check2_out auth_check2_out;

struct shttpd_conn {
	char *dirname;
	char *authorization;
	char *hostdir;
	char *remoteuser;
	char *encodedurl;
	char *useragent;
	char *charset;
	char *protocol;
	char *p3p;
	char *response;
	int global_passwd;
	int vhost;
	int maxremoteuser;
	int method;
	int should_linger;
	int status;
	int mime_flag;
	int max_age;
	int got_range;
	int maxresponse;
	int responselen;
	long first_byte_index;
	long last_byte_index;
	long bytes_to_send;
	long range_if;
};
typedef struct shttpd_conn shttpd_conn;


#define AUTHPROG 0x31240000
#define AUTHVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define auth_check2 1
extern  auth_check2_out * auth_check2_1(shttpd_conn *, CLIENT *);
extern  auth_check2_out * auth_check2_1_svc(shttpd_conn *, struct svc_req *);
extern int authprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define auth_check2 1
extern  auth_check2_out * auth_check2_1();
extern  auth_check2_out * auth_check2_1_svc();
extern int authprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_auth_check2_out (XDR *, auth_check2_out*);
extern  bool_t xdr_shttpd_conn (XDR *, shttpd_conn*);
extern  bool_t xdr_shttpd_conn (XDR *, shttpd_conn*);

#else /* K&R C */
extern bool_t xdr_auth_check2_out ();
extern bool_t xdr_shttpd_conn ();
extern bool_t xdr_shttpd_conn ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AUTHCHECK_H_RPCGEN */
