/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "authcheck.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

auth_check2_out *
auth_check2_1(shttpd_conn *argp, CLIENT *clnt)
{
	static auth_check2_out clnt_res;
	printf("in authcheck_clnt.c, auth_check2_1 invoked\n");

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, auth_check2,
		(xdrproc_t) xdr_shttpd_conn, (caddr_t) argp,
		(xdrproc_t) xdr_auth_check2_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
